### ISSUE TITLE
Base Folder

### ISSUE THREAD

**Issue by kondanta** [Egomination/MangApplizer-Beta#4] opened 2017-11-23 11:12 UTC
- If the base folder `imgs` is not available, it gives an error which we haven't handled yet.

**Comment by sasalx** [comment] 2017-11-23 13:34
The problem is for some reason forEach takes one more item which is empty. That is why script works fine but gives an error at the end while trying to do run with empty input a.k.a. bad domain name.

**Also the real bug is not about imgs folder.**

@kondanta

**Comment by kondanta** [comment] 2017-11-23 14:17
`	      	if(info){
	      		list.push(info);
	      	}` 
- With this, NaN values can be eliminated.

@sasalx

**Comment by sasalx** [comment] 2017-11-23 14:28
Fixed with #5 .

**Comment by sasalx** [comment] 2017-12-17 20:10
We have the same problem for viewer. Need a fix for that as well.

**Comment by sasalx** [comment] 2017-12-25 17:28
Fixed with #31. _Again_

**Closed as completed by sasalx** 2017-12-25 17:28 UTC
Labels: Bug
